### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen - lib/data/villages.csv

### ISSUE THREAD

**Issue by muhammadyana** [dimasjt/indonesia#3]
Hello, i have installed the gem but when run in console there is an error.
`Errno::ENOENT: No such file or directory @ rb_sysopen - lib/data/villages.csv`
![image](https://user-images.githubusercontent.com/7847990/60067242-12bd4c00-9734-11e9-86ce-6b824338e133.png)

**Comment by kwhandy** [comment]
Hi @muhammadyana are you using the v0.5.0 or the latest(v0.6.0)?

**Comment by muhammadyana** [comment]
Fixed by use v0.6.0.
